@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWIwYWlzeXAwMDAwY2NveWFhem1tbzllIiwiZW1haWwiOiJna3NrdGwxMjNAbmF2ZXIuY29tIiwibmlja25hbWUiOiLrgpjripTslbzrqYvsp4TquIjrtpXslrQiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0ODY4NjcyMSwiZXhwIjoxNzQ4Njg3NjIxfQ.6m1o2jSwmKCQX93JtSBxVg_Dz8SoGLs9DOj3WFAX4Ic
### 챌린지 쿼리 조회
GET http://localhost:8080/challenges?page=3&pageSize=4&category=&docType=&keyword=ㅊㄹㅈ&status=

### 챌린지 등록(신청)
POST http://localhost:8080/challenges
Content-Type: application/json
Cookie:  accessToken={{accessToken}}

{
  "title": "챌린지 등록",
  "description": "모두 함께 도전해봅시다",
  "category": "Modern JS",
  "docType": "블로그",
  "originalUrl": "https://test1-url.com",
  "deadline": "2026-11-28T00:30:21.142Z",
  "maxParticipant": 5
}

### (수정 필요) > 인증되지 않은 사용자입니다 에러, 쿠키로 되는지 확인
### 챌린지 수정
PUT http://localhost:8080/challenges/3
Content-Type: application/json
Cookie:  accessToken={{accessToken}}

{
    "title": "챌린지 수정",
    "description": "테스트 챌린지, test challenge 등록",
    "category": "Next.js",
    "docType": "공식문서",
    "originalUrl": "https://test1-url.com",
    "deadline": "2025-11-28T00:30:21.142Z",
    "maxParticipant": 5
}

### 챌린지 상세 조회
GET http://localhost:8080/challenges/20


### (수정 필요) 인증되지 않은 사용자입니다 오류, 쿠키로 되는지 확인
### 챌린지 신청 취소
DELETE http://localhost:8080/challenges/24
Content-Type: application/json
Cookie:  accessToken={{accessToken}}